### ISSUE TITLE
how do you debug Potentially unhandled rejection [1] Error?

### ISSUE THREAD

**Issue by hayesmaker** [mr-doc/mr-doc#123] opened 2016-12-21 20:28 UTC
#### Is it a problem: yes

```
doxx --source src/app --debug --target docs
Doxx [info]: ⠋ Creating home directory
Potentially unhandled rejection [1] Error: Name must be lowercase, can contain digits, dots, dashes, "@" or spaces
```

**Comment by docwhite** [comment] 2017-03-06 16:29
I am having the same problem here

**Comment by voidit** [comment] 2018-03-15 15:35
Same here

**Comment by FGRibreau** [comment] 2018-03-17 15:19
cc @iwatakeshi

**Comment by iwatakeshi** [comment] 2018-03-17 16:07
Sorry guys, it will take some time for me to look into this issue. In the mean time, can you create a sample app that has a similar setup and post the link in the comments? I’ll will then fork the project and debug it. Thanks.

**Comment by iwatakeshi** [comment] 2018-08-24 16:15
Closing this issue since no repo with a reproducible error was provided.

**Closed by iwatakeshi** 2018-08-24 16:15 UTC
